#!/bin/sh

query="0"
while [ "$#" -gt 0 ]; do
  query="$query + $1"
  shift
done
s=$(psql -c "select $query" -t -U postgres)
echo $s

exit
s=0
while [ "$#" -gt 0 ]; do
  s=$(( s + $1 ))
  shift
done
echo $s
